project_id = "bquxkkaipevuakmqqilk"

[functions.extract-medication]
verify_jwt = true

[functions.submit-feedback]
verify_jwt = true

[functions.check-drug-interactions]
verify_jwt = true

[functions.secure-image-upload]
verify_jwt = true